controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
open_api_server:
    resource: "@OpenAPIServerBundle/Resources/config/routing.yaml"
app_logout:
    path: /logout
    methods: POST
